### ISSUE TITLE
CRASH REPORT Process <> with 0 neighbours exited with reason: call to undefined function application

### ISSUE THREAD

**Issue by topspeedbell** [FlowForwarding/LINC-Switch#360]
I updated the LINC-Switch and configured the file of sys.config. there is a creash report like this:
 
(linc@raspberrypi)1> 21:28:24.597 ^[[1;37m[info] Created port: {port,2,[{queues_status,disabled},{queues,[]},{config,{port_configuration,undefined,up,false,false,false}},{features,{features,undefined,'100Mb-FD',true,copper,unsupported}},{interface,"eth1"}]}^[[0m
21:28:24.827 ^[[1;37m[info] Created port: {port,3,[{queues_status,disabled},{queues,[]},{config,{port_configuration,undefined,up,false,false,false}},{features,{features,undefined,'100Mb-FD',true,copper,unsupported}},{interface,"eth2"}]}^[[0m
21:28:25.078 ^[[1;37m[info] Created port: {port,4,[{queues_status,disabled},{queues,[]},{config,{port_configuration,undefined,up,false,false,false}},{features,{features,undefined,'100Mb-FD',true,copper,unsupported}},{interface,"wlan0"}]}^[[0m
21:28:25.094 ^[[1;31m[error] CRASH REPORT Process <0.196.0> with 0 neighbours exited with reason: call to undefined function application:get_env(of_protocol, no_multipart, false) in gen_server:init_it/6 line 328

Your help is appreciated!

**Comment by marcsugiyama** [comment]
It looks like our documentation is out of date.  Please try building with R16 (or newer) version of Erlang.  application:get_env/3 (e.g., with three arguments) appeared in R16.

**Comment by marcsugiyama** [comment]
Updated README.
