### ISSUE TITLE
Can the USB-to-RJ45 work well in the LINC-Switch in a PC?

### ISSUE THREAD

**Issue by topspeedbell** [FlowForwarding/LINC-Switch#364]
I installed the LINC-Switch in a PC. There are only one eth port in the PC, So I have to expand the eth ports with USB-to-RJ45. But the host and the Server can only ping each other through the LINC-Switch, and can not finish the three-shank hands of tcp.
So my question is if the USB-to-RJ45 can work well in the LINC-Switch?

I'm looking forward to your help!
thanks very much!

**Comment by mentels** [comment]
I would suggest using Virtual Machines running for example on Virtual Box
and build a topology u like. That way you won't be limited to one interface.

Another option, if you are using linux, is to use TUN/TAP interfaces.

Regards,

On Thu, Jun 25, 2015 at 5:09 AM, topspeedbell <notifications@github.com>
wrote:

> I installed the LINC-Switch in a PC. There are only one eth port in the
> PC, So I have to expand the eth ports with USB-to-RJ45. But the host and
> the Server can only ping each other through the LINC-Switch, and can not
> finish the three-shank hands of tcp.
> So my question is if the USB-to-RJ45 can work well in the LINC-Switch?
>
> I'm looking forward to your help!
> thanks very much!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FlowForwarding/LINC-Switch/issues/364>.
>



-- 
Szymon Mentel
Erlang Solutions Ltd.

**Comment by topspeedbell** [comment]
Thanks for your help!
I have used VM running for the example on Linux. But now I want to setup a physical test-bed.

BR

**Comment by topspeedbell** [comment]
It can work. 
thanks!
