### ISSUE TITLE
Do I need to set the ip_forward?

### ISSUE THREAD

**Issue by topspeedbell** [FlowForwarding/LINC-Switch#366]
Hi,

I install the linc switch in a linux PC. Do I need to change the net.ipv4.ip_forward =0 to net.ipv4.ip_forward =1 ?

thanks!

BR
zhao

**Comment by mentels** [comment]
This flag is not required for LINC. It enables IP routing in the system.

**Comment by topspeedbell** [comment]
OK, thanks!
